# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Define a job to be invoked later in a workflow.
jobs:
  print-hello:
    # Specify the execution environment.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - run: echo hello

  print-world:
    # Specify the execution environment
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - run: echo world

  print-name:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run: echo I am called $MY_NAME
# Invoke jobs via workflows
workflows:
  #Name the workflow "welcome"
  welcome:
    #Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-name:
          requires:
            - print-world
