# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Define a job to be invoked later in a workflow.
jobs:
  save-hello-world-output:
    # Specify the execution environment.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print-output-file:
    # Specify the execution environment
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

# Invoke jobs via workflows
workflows:
  #Name the workflow "my-workflow"
  my-workflow:
    jobs:
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output
